### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by nicolascolla**
The icon should be a perfect square to respect the style of other apps.

### CODE REVIEW

**Comment by nicolascolla** [comment]
> uh i don't see why all icons have to be perfect squares?

It breaks the theming otherwise:

photo_2021-10-30_04-03-55

**Comment by Fuseteam** [comment]
none of those are perfect squares tho they are more squarcles

**Comment by nicolascolla** [comment]
> none of those are perfect squares tho they are more squarcles

The system cuts the borders that way automatically. The icons inside a click file are always squares.

**Comment by Fuseteam** [comment]
hmmm i think then that the icon should be made bigger rather than

**Comment by alefnode** [comment]
so which are the correct size for icons, do you know? there are any documentation about that?

**Comment by nicolascolla** [comment]
> so which are the correct size for icons, do you know? there are any documentation about that?

Usually, I use a 600px+ .png image. That seems to be enough. The icon I have submitted seems to be enough, at least on my Redmi Note 9 and a Raspberry Pi with a 1080p monitor. Some apps use a scalable .svg, which I guess is optimal.

**Comment by Fuseteam** [comment]
this might help according to @cibersheep https://docs.ubports.com/en/latest/humanguide/design-concepts/app-icon-design.htm

**Pull request merged**
